POST http://localhost:3000/avatar
Content-Type: application/json

[
  {
    "variation": "6491fcd62c1a83f95d14e5ec"
  },
  {
  }
]

###
POST http://localhost:3000/avatar/create
Content-Type: application/json

[
  {
    "variation": "64943f502d9bc32598a3706b",
    "color": "#f1d1ba"
  },
  {
    "variation": "64944b9edea8c6aa848b713a",
    "color": "#8fd4ff"
  },

  {
    "variation": "6494513e7c1939556fd695c2",
     "color": null,
     "colorless": true
  }
  
]

###
POST http://localhost:3000/avatar
Content-Type: application/json

[]

###
GET http://localhost:3000/avatar/create

###
GET http://localhost:3000/avatar/all
