POST http://localhost:3000/avatar
Content-Type: application/json

[
  {
    "variation": "6491fcd62c1a83f95d14e5ec"
  },
  {
  }
]

###
POST http://localhost:3000/avatar/create
Content-Type: application/json

[
    {
        "variation": "64943f502d9bc32598a3706b",
        "color": "#f99664"
    },
    {
        "variation": "64944b9edea8c6aa848b713b",
        "color": "#f0f"
    },
    {
        "variation": "64954795be98c615c564d433",
        "color": null
    },
    {
        "variation": "64954da228eb0d9386e7507b",
        "color": null
    }
]

###
POST http://localhost:3000/avatar
Content-Type: application/json

[]

###
GET http://localhost:3000/avatar/create

###
GET http://localhost:3000/avatar/all